# Server configuration
server:
  port: 8090
  contextPath:

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:

    dbcp2:
      fast-fail-validation:
#  data.mongodb:
#    host: localhost
#    port: 27017
#    database: springboot

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

emailList: >
  @fudan.edu.cn,
  @qq.com

# JWT
jwt:
  header: Authorization
  secret: "fduprojectmgmtpjfduprojectmgmtpjfduprojectmgmtpjfduprojectmgmtpjfduprojectmgmtpjfduprojectmgmtpj"
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      login: auth/login
      refresh: refresh
      register: auth/register
      registrationConfirm: auth/registrationConfirm
      updatePass: auth/update
      resetPass: auth/reset
      requestResetPass: auth/requestReset

# check time
checkTime: 180000

# Other api routes
api:
  event:
    detail: api/event/detail
    home-slides: api/event/home-slides
    home-flow: api/event/home-flow
    add: api/event/add
    cancel: api/event/cancel
    checkin: api/event/checkin
    nearby: api/event/nearby
    search: api/event/search
  tag:
    add: api/tag/add
    list: api/tag/list
  user:
    join: api/user/join
    quit: api/user/quit
    joined: api/user/joined
    released: api/user/released
    getDetail: api/user/get
    checkIn: api/user/checkIn
    checkOut: api/user/checkOut
    updateName: api/user/updateName
    updateImg: api/user/updateImg
    current: api/user/current
  image:
    get:
      event: api/eventImg/get
      user: api/userImg/get
  notify:
    list: api/notif/notif-list
    read: api/notif/read

download:
  url: download
  resource: static/pj.apk
  filename: pj.apk

webSocket:
  stomp: /websocket
  prefix: /queue
  newNotif: /notif

# result messages
resultMessage:
  error:
    auth:
      login: "Bad email or password"
  success:
    auth:
      register: "Register success"
      registrationConfirm: "Registration confirm success"
      update: "Update success"

messages:
  cancelEvent:
    time:
      initiator: "对不起，由于您发布的这个活动 %event% 在规定时间内没有达到人数最低要求，系统已自动取消该活动，给您生活娱乐带来了很大的不便，请您谅解！"
      others: "对不起，由于您参加的这个活动 %event% 在规定时间内没有达到人数最低要求，系统已自动取消该活动，给您生活娱乐带来了很大的不便，请您谅解！"
    user:
      initiator: "您发布的活动已取消"
      others: "对不起，您参加的这个活动 %event% 已经被发起人取消，给您生活娱乐带来了很大的不便，请您谅解！"
  resetPass:  "请在重置密码界面输入验证码,\n 你的验证码为： %code%"

imagePathTitle: "event-images"

verifyCodes: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"
verifySize: 6

defaultNickname: "新用户"